from unittest.mock import call

import pytest
from pyghmi.ipmi.sdr import SensorReading

from chronus.domain.system_sample import SystemSample
from chronus.SystemIntegration.system_service_interfaces.ipmi_system_service import (
    IpmiSystemService,
)


@pytest.fixture
def mock_ipmi(mocker):
    mocker.patch("pyghmi.ipmi.private.localsession.Session")
    mocker.patch("pyghmi.ipmi.command.Command.get_sensor_reading", return_value=get_sensor_data)

    def mock_reading(sensor_reading: SensorReading):
        return mocker.patch(
            "pyghmi.ipmi.command.Command.get_sensor_reading", return_value=sensor_reading
        )

    return mock_reading


def test_returns_system_sample(mock_ipmi):
    # Arrange
    random_sample = get_sensor_data[0]
    mock_ipmi(random_sample)
    ipmi = IpmiSystemService()

    # Act
    sample = ipmi.sample()

    # Assert
    assert sample is not None
    assert isinstance(sample, SystemSample)


def test_gets_power_draw(mock_ipmi):
    # Arrange
    mock = mock_ipmi(
        SensorReading(
            {
                "cpu_name": "System Level",
                "type": "Power",
                "id": 1,
                "value": 20.0,
                "imprecision": 1.5,
                "states": [],
                "state_ids": [],
                "health": 0,
            },
            "W",
        )
    )
    ipmi = IpmiSystemService()

    # Act
    sample = ipmi.sample()

    # Assert
    print(mock.call_args_list)
    assert call("Total_Power") in mock.call_args_list
    assert sample.current_power_draw == 20.0


def test_gets_cpu_temp(mock_ipmi):
    # Arrange
    mock = mock_ipmi(
        SensorReading(
            {
                "cpu_name": "CPU_Temp",
                "type": "Temperature",
                "id": 3,
                "value": 54.0,
                "imprecision": 1.5,
                "states": [],
                "state_ids": [],
                "health": 0,
            },
            "°C",
        )
    )
    ipmi = IpmiSystemService()

    # Act
    sample = ipmi.sample()

    # Assert
    assert call("CPU_Temp") in mock.call_args_list
    assert sample.cpu_temp == 54.0


def test_gets_cpu_power(mock_ipmi):
    # Arrange
    mock = mock_ipmi(
        SensorReading(
            {
                "cpu_name": "CPU_Power",
                "type": "Power",
                "id": 3,
                "value": 54.0,
                "imprecision": 1.5,
                "states": [],
                "state_ids": [],
                "health": 0,
            },
            "W",
        )
    )
    ipmi = IpmiSystemService()

    # Act
    sample = ipmi.sample()

    # Assert
    assert call("CPU_Power") in mock.call_args_list
    assert sample.cpu_power == 54.0


get_sensor_data = [
    SensorReading(
        {
            "value": 35.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Inlet_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 39.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Outlet_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 55.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "CPU_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 49.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "DIMMG1_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 50.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "DIMMG2_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 42.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "CPU_VR_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 46.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "SOC_VR_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 46.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "VDD_ABCD_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 47.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "VDD_EFGH_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 37.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "PSU1_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 36.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "PSU2_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Riser1_GPU_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Riser2_GPU_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Riser3_GPU_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Retimer1_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Retimer2_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 39.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "PCIe1_Inlet_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 42.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "PCIe2_Inlet_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "MID_BP1_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "MID_BP2_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Rear_BP_Temp1",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 36.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Riser_Int_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 38.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Riser_1_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": None,
            "cpu_name": "Riser_2_Temp",
            "type": "Temperature",
            "unavailable": 1,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": None,
            "cpu_name": "Riser_3_Temp",
            "type": "Temperature",
            "unavailable": 1,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Front_NVME_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "MID_NVME_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 0.0,
            "states": [],
            "state_ids": [],
            "units": "°C",
            "imprecision": 1.5,
            "cpu_name": "Rear_NVME_Temp",
            "type": "Temperature",
            "unavailable": 0,
            "health": 0,
        },
        "°C",
    ),
    SensorReading(
        {
            "value": 1.1716000000000002,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.0029000000000001247,
            "cpu_name": "CPU_VDDCR",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 0.8294,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.0029000000000000137,
            "cpu_name": "SOC_VDDCR",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 1.2064,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.0028999999999999027,
            "cpu_name": "VDD_MEM_ABCD",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 1.2064,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.0028999999999999027,
            "cpu_name": "VDD_MEM_EFGH",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 2.6,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.00649999999999995,
            "cpu_name": "VDD_VPP_ABCD",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 2.587,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.00649999999999995,
            "cpu_name": "VDD_VPP_EFGH",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 5.016,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.011999999999999567,
            "cpu_name": "P5V_VDD_RearMID",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 3.1799999999999997,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.009999999999999787,
            "cpu_name": "P3V_BAT",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 0.903,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.010499999999999954,
            "cpu_name": "VDDCR_SOC_DUAL",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 5.096,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.0389999999999997,
            "cpu_name": "VDD_5_DUAL",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 3.349,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.025500000000000078,
            "cpu_name": "VDD_33_RUN",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 0.595,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.010499999999999954,
            "cpu_name": "VDD_VTT_EFGH",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 1.815,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.01649999999999996,
            "cpu_name": "VDD_18_RUN",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 1.8370000000000002,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.01650000000000018,
            "cpu_name": "VDD_18_DUAL",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 5.148,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.0389999999999997,
            "cpu_name": "VDD_5_RUN",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 11.834,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.09149999999999991,
            "cpu_name": "P12V_RUN",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 0.595,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.010499999999999954,
            "cpu_name": "VDD_VTT_ABCD",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 1.155,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.010499999999999954,
            "cpu_name": "P1V15_BMC",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 1.2040000000000002,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.010500000000000176,
            "cpu_name": "P1V2_DDR_BMC",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 3.366,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.025500000000000078,
            "cpu_name": "VDD_33_DUAL",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 18221.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN1_F_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 15481.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN1_R_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 17947.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN2_F_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 15207.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN2_R_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 18084.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN3_F_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 15344.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN3_R_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 23153.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN4_F_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 19454.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN4_R_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 23427.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN5_F_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 19591.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN5_R_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 22879.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN6_F_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 19865.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN6_R_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 23427.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN7_F_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 19728.0,
            "states": [],
            "state_ids": [],
            "units": "RPM",
            "imprecision": 205.5,
            "cpu_name": "FAN7_R_Speed",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "RPM",
    ),
    SensorReading(
        {
            "value": 108.0,
            "states": [],
            "state_ids": [],
            "units": "W",
            "imprecision": 9.0,
            "cpu_name": "PSU1_PIN",
            "type": "Power",
            "unavailable": 0,
            "health": 0,
        },
        "W",
    ),
    SensorReading(
        {
            "value": 100.0,
            "states": [],
            "state_ids": [],
            "units": "W",
            "imprecision": 12.0,
            "cpu_name": "PSU1_POUT",
            "type": "Power",
            "unavailable": 0,
            "health": 0,
        },
        "W",
    ),
    SensorReading(
        {
            "value": 228.14,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 1.829999999999984,
            "cpu_name": "PSU1_VIN",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 12.200000000000001,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.15000000000000036,
            "cpu_name": "PSU1_VOUT",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 0.5,
            "states": [],
            "state_ids": [],
            "units": "% A",
            "imprecision": 0.07500000000000001,
            "cpu_name": "PSU1_IIN",
            "type": "Current",
            "unavailable": 0,
            "health": 0,
        },
        "% A",
    ),
    SensorReading(
        {
            "value": 96.0,
            "states": [],
            "state_ids": [],
            "units": "W",
            "imprecision": 9.0,
            "cpu_name": "PSU2_PIN",
            "type": "Power",
            "unavailable": 0,
            "health": 0,
        },
        "W",
    ),
    SensorReading(
        {
            "value": 84.0,
            "states": [],
            "state_ids": [],
            "units": "W",
            "imprecision": 12.0,
            "cpu_name": "PSU2_POUT",
            "type": "Power",
            "unavailable": 0,
            "health": 0,
        },
        "W",
    ),
    SensorReading(
        {
            "value": 226.92000000000002,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 1.8300000000000125,
            "cpu_name": "PSU2_VIN",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 12.200000000000001,
            "states": [],
            "state_ids": [],
            "units": "V",
            "imprecision": 0.15000000000000036,
            "cpu_name": "PSU2_VOUT",
            "type": "Voltage",
            "unavailable": 0,
            "health": 0,
        },
        "V",
    ),
    SensorReading(
        {
            "value": 0.45,
            "states": [],
            "state_ids": [],
            "units": "% A",
            "imprecision": 0.07500000000000001,
            "cpu_name": "PSU2_IIN",
            "type": "Current",
            "unavailable": 0,
            "health": 0,
        },
        "% A",
    ),
    SensorReading(
        {
            "value": 61.0,
            "states": [],
            "state_ids": [],
            "units": "W",
            "imprecision": 1.5,
            "cpu_name": "CPU_Power",
            "type": "Power",
            "unavailable": 0,
            "health": 0,
        },
        "W",
    ),
    SensorReading(
        {
            "value": 25.0,
            "states": [],
            "state_ids": [],
            "units": "W",
            "imprecision": 1.5,
            "cpu_name": "MEM_Power",
            "type": "Power",
            "unavailable": 0,
            "health": 0,
        },
        "W",
    ),
    SensorReading(
        {
            "value": 186.0,
            "states": [],
            "state_ids": [],
            "units": "W",
            "imprecision": 9.0,
            "cpu_name": "Total_Power",
            "type": "Power",
            "unavailable": 0,
            "health": 0,
        },
        "W",
    ),
    SensorReading(
        {
            "value": 67.0,
            "states": [],
            "state_ids": [],
            "units": "CFM",
            "imprecision": 1.5,
            "cpu_name": "Airflow_rate",
            "type": "Other",
            "unavailable": 0,
            "health": 0,
        },
        "CFM",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Redundant"],
            "state_ids": [723712],
            "units": "",
            "imprecision": None,
            "cpu_name": "Cooling_Status",
            "type": "Other",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PSU1_Fan_Status",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PSU2_Fan_Status",
            "type": "Fan",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [552704],
            "units": "",
            "imprecision": None,
            "cpu_name": "PSU1_Status",
            "type": "Power Supply",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [552704],
            "units": "",
            "imprecision": None,
            "cpu_name": "PSU2_Status",
            "type": "Power Supply",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PS_Redundant",
            "type": "Power Supply",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PS_Mismatch",
            "type": "Power Supply",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE1_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE2_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE3_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE4_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE5_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE6_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE7_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE8_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE9_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "ALL_NVMEs_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "CPU_ALERT",
            "type": "Processor",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "CPU_Prochot",
            "type": "Processor",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "CPU_Thermaltrip",
            "type": "Processor",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "CPU_MCA_Error",
            "type": "Processor",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "TPM_Binding",
            "type": "Physical Security",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "TPM_Policy",
            "type": "Physical Security",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "TPM_Toggling",
            "type": "Physical Security",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "OCP_AER",
            "type": "Critical interrupt",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Slot/connector installed"],
            "state_ids": [2191106],
            "units": "",
            "imprecision": None,
            "cpu_name": "M2_Card_Fault",
            "type": "Slot/Connector",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [814854],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_1",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_2",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [814854],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_3",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_4",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [814854],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_5",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_6",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [814854],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_7",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_8",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_9",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [814854],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_10",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_11",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [814854],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_12",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_13",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [814854],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_14",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_15",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [814854],
            "units": "",
            "imprecision": None,
            "cpu_name": "DIMM_16",
            "type": "Memory",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Connected"],
            "state_ids": [1797888],
            "units": "",
            "imprecision": None,
            "cpu_name": "Front_BP1_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Front_BP2_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Front_BP3_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Middle_BP1_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Middle_BP2_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Rear_BP_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "VGA_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Connected"],
            "state_ids": [1797888],
            "units": "",
            "imprecision": None,
            "cpu_name": "Front_USB_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Connected"],
            "state_ids": [1797888],
            "units": "",
            "imprecision": None,
            "cpu_name": "M2_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Fan_Type_Err",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Chassis_Intr",
            "type": "Physical Security",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Intr_Cable",
            "type": "Cable/Interconnect",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [1509377],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE1_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE2_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE3_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [1509377],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE4_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE5_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE6_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE7_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE8_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "PCIE9_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [1509377],
            "units": "",
            "imprecision": None,
            "cpu_name": "OCP_Status",
            "type": "Add-in Card",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Online"],
            "state_ids": [2256640],
            "units": "",
            "imprecision": None,
            "cpu_name": "ACPI_State",
            "type": "System ACPI Power State",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Watchdog2",
            "type": "Watchdog",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Power_Button",
            "type": "Button/switch",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Event_Log",
            "type": "Event Log Disabled",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [880384],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive0",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [880384],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive1",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive2",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive3",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive4",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive5",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive6",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive7",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive8",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive9",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive10",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive11",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive12",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive13",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive14",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive15",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive16",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive17",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive18",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive19",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive20",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive21",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive22",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive23",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive24",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive25",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive26",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive27",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive28",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive29",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive30",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "Drive31",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": ["Present"],
            "state_ids": [880384],
            "units": "",
            "imprecision": None,
            "cpu_name": "M2_Drive0",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "M2_Drive1",
            "type": "Drive Bay",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
    SensorReading(
        {
            "value": None,
            "states": [],
            "state_ids": [],
            "units": "",
            "imprecision": None,
            "cpu_name": "BMC_Boot_Up",
            "type": "Microcontroller/Coprocessor",
            "unavailable": 0,
            "health": 0,
        },
        "",
    ),
]
